### PR TITLE
[#7] fix sumo_db dependency

### LINKED ISSUE #7: Fix sumo_db dependency
Fix the adapter in order to fetch sumo_db from hex.pm

### PR DESCRIPTION
**Pull request by ferigis**
sumo_db is fetched from hex.pm [close #7]

### CODE REVIEW

File: test/find_SUITE.erl [hunk 1]
```diff
@@ -18,7 +18,7 @@
 %%%=============================================================================
 
 -spec all() -> [atom()].
-all() -> [find_by_sort, find_all_sort].
+all() -> [].  %% @todo recover the whole list of test cases when #257
```
Comment (elbrujohalcon) [inline test/find_SUITE.erl]: tiny detail: specify that the issue is inaka/sumo_db#257 and not #257 (in this repo)
